### ISSUE TITLE
Comments count is not working

### ISSUE THREAD

**Issue by briankung** [briankung/projectcredo#114]

**Comment by wsf246** [comment]
is this just the javascript that shows the count or also the vote count is different than cached?

**Comment by briankung** [comment]
I haven't looked at it that deeply yet. Tbh now I'm wondering if there just
weren't any comments. But I think I was testing the seeds branch with
comments.

**Comment by wsf246** [comment]
cool, well the javascript isn't picking the comments count regardless so ill fix that first.  I opened a new branch.

**Comment by briankung** [comment]
Maybe there's a better way to do the comments count. I don't remember why
we were doing it that way, to begin with. Do you?

**Comment by wsf246** [comment]
yea, we wanted to change to javascript instead of going through closure tree and counting up and down the hierarchy.

**Comment by briankung** [comment]
Oh. There's probably something we can use to count the comments on the
backend.

**Comment by briankung** [comment]
Maybe sum up self_and_descendants.count per top level comment.

**Comment by briankung** [comment]
Sorry, it was my dumb idea to count the divs. On second thought, that's a
really dumb hack XD

**Comment by briankung** [comment]
For a fancier option, we could also cache the comments count on the
reference itself. But not necessary right now.
