### ISSUE TITLE
timing out

### ISSUE THREAD

**Issue by wsf246** [briankung/projectcredo#135]
**Problem:** 
Getting this error locally, don't know if it's because of the jquery fuckery I've been doing, but it's screwing with my docker:

ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

Maybe something with tty?

**Comment by briankung** [comment]
Yeah that's the thing I told you about. Just docker attach like I show you
in the screencast I sent earlier

**Comment by wsf246** [comment]
Ah man.. sorry.
