### ISSUE TITLE
"Validation failed: User must exist" when I add a list to homepage

### ISSUE THREAD

**Issue by wsf246** [briankung/projectcredo#20]
After signing up and adding a list to my homepage, I get "Validation failed: User must exist"

 Extracted source (around line #6):

4
5
6
7
8
9

  def create
    @pinned_lists << List.find(list_params[:id])
    redirect_to :back
  end

**Comment by briankung** [comment]
Delete your old lists or go into console and associate them to a user

**Comment by wsf246** [comment]
yup, just about to do that.  I'm going to just reseed using your seed.

**Comment by wsf246** [comment]
works now, I'm closing this.

**Comment by briankung** [comment]
Sounds good

On Tue, Jul 12, 2016 at 10:57 PM, wsf246 notifications@github.com wrote:

> yup, just about to do that. I'm going to just reseed using your seed.
> 
> On Tue, Jul 12, 2016 at 10:49 PM, Brian Kung notifications@github.com
> wrote:
> 
> > Delete your old lists or go into console and associate them to a user
> > 
> > On Tue, Jul 12, 2016, 10:46 PM wsf246 notifications@github.com wrote:
> > 
> > > After signing up and adding a list to my homepage, I get "Validation
> > > failed: User must exist"
> > > 
> > > Extracted source (around line #6
> > > https://github.com/briankung/projectcredo/issues/6):
> > > 
> > > 4
> > > 5
> > > 6
> > > 7
> > > 8
> > > 9
> > > 
> > > def create
> > > @pinned_lists << List.find(list_params[:id])
> > > redirect_to :back
> > > end
> > > 
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/briankung/projectcredo/issues/20, or mute the
> > > thread
> > > <
> > 
> > https://github.com/notifications/unsubscribe/ACtGxz5K4jNAZUmrB2R7LftuU3RjIcHIks5qVF94gaJpZM4JLCWq
> > 
> > > .
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> > https://github.com/briankung/projectcredo/issues/20#issuecomment-232249481
> > ,
> > or mute the thread
> > <
> > https://github.com/notifications/unsubscribe/ACKsZASF8Kgah4-SskTjEgxSBXIVWl5Rks5qVGA8gaJpZM4JLCWq
> > 
> > .
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/briankung/projectcredo/issues/20#issuecomment-232250371,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACtGx-uWGqDMv8hOYEJSa5ZabvH3FyEHks5qVGI6gaJpZM4JLCWq
> .

## 

Brian Kung
http://about.me/briankung/
http://www.facebook.com/brian.kung http://www.linkedin.com/in/briankung
http://www.twitter.com/briankung

BE A UNICORN!
