### ISSUE TITLE
A user should be able to associate an Author with a Study

### ISSUE THREAD

**Issue by briankung** [briankung/projectcredo#25]

**Comment by briankung** [comment]
This needs a lot of UI work and thinking. "Brainstorming," if you must.

**Comment by wsf246** [comment]
Do you think we should close this for now?  I know we want to do some revamping, but we have an interim solution.  

Also, good call on deleting the branch and closing the issue.  The process is good.

**Comment by briankung** [comment]
Yeah, I'd close it.
