### ISSUE TITLE
Latest updated list should show up on top

### ISSUE THREAD

**Issue by wsf246** [briankung/projectcredo#44]
I think this is a fix via scope of lists.  Should be a quick enhancement.

**Comment by briankung** [comment]
This might prove hairy, but sort by updated at might do the trick. I only say this because Model.last isn't sorting by date, but it might just default to the highest integer primary ID.

**Comment by wsf246** [comment]
when I update a list right now, it sends it to the bottom so I think something is happening.  I'll play around and see if its easy to do, but won't sweat it if not.
