### ISSUE TITLE
A user should be able to add Papers to Lists from homepage

### ISSUE THREAD

**Issue by briankung** [briankung/projectcredo#5]
On the homepage or otherwise, wherever you see a list

You should be able to add papers just by DOI for now.

**Comment by briankung** [comment]
Is this done?

**Comment by wsf246** [comment]
for now, the functionality only exists on list show.  I was holding off on adding to list index and homepage until you had finished the functionality.  I think once we have that feature in those places, we can close this.

**Comment by briankung** [comment]
Ah gotcha

On Sun, Jul 10, 2016 at 1:24 PM, wsf246 notifications@github.com wrote:

> for now, the functionality only exists on list show. I was holding off on
> adding to list index and homepage until you had finished the functionality.
> I think once we have that feature in those places, we can close this.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/briankung/projectcredo/issues/5#issuecomment-231603210,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACtGxxRjBetw7_WzJiBA7TiV8aGeK49Vks5qUTjbgaJpZM4I_keU
> .

## 

Brian Kung
http://about.me/briankung/
http://www.facebook.com/brian.kung http://www.linkedin.com/in/briankung
http://www.twitter.com/briankung

BE A UNICORN!
