### ISSUE TITLE
A user should be able to reorder lists

### ISSUE THREAD

**Issue by briankung** [briankung/projectcredo#57]
Potentially by:
- Votes
- Last updated

etc

**Comment by wsf246** [comment]
I think we should have a default order "credo order" be something like reddit's that include's time and votes in addition to letting people choose order by purely votes and last_updated

https://medium.com/hacking-and-gonzo/how-reddit-ranking-algorithms-work-ef111e33d0d9#.p8drg5o6g

![image](https://cloud.githubusercontent.com/assets/2272356/17870938/1dcf9198-687f-11e6-9360-36ccfc199bda.png)

we won't need to worry about downvotes or overall negative votes so it makes our algorithm much easier.

For lists, we can adjust by update time.  

For papers, we can use the publication date.  I would say we don't as heavily weight time for papers as reddit, but we can play with a few weightings to see what give us the best results.
