### ISSUE TITLE
When adding a paper by DOI, additional information should be pulled from a third party source

### ISSUE THREAD

**Issue by briankung** [briankung/projectcredo#6]
Probably Pubmed to grab title, authors, etc.

**Comment by briankung** [comment]
http://www.fredtrotter.com/2014/11/14/hacking-on-the-pubmed-api/

**Comment by briankung** [comment]
This was closed automatically via my comment. Are you still working on it?

**Comment by wsf246** [comment]
yea, I think the author and abstract are prob pieces for this.
